### ISSUE TITLE
Vagrant 2.0.3 deb download

### ISSUE THREAD

**Issue by Spurlos** [wolfgang42/vagrant-deb#11]
Currently APT server tells that there is an updated version, but fails on fetching the .deb file with `E: Failed to fetch https://vagrant-deb.linestarve.com/pool/any/main/v/vagrant/vagrant_2.0.3_amd64.deb  404  Not Found`. Looks like the meta data is already there, but the file it self went missing (still processing?)

Can you please check\explain why this is happening? Currently this behavior is breaking default `apt upgrade` process.
![image](https://user-images.githubusercontent.com/667533/37541544-b19ba56e-2963-11e8-962d-85d91a375f59.png)

Thanks!

**Comment by maxolasersquad** [comment]
https://vagrant-deb.linestarve.com/pool/any/main/v/vagrant/vagrant_2.0.3_amd64.deb is giving a 404.

**Comment by JanSchnacki** [comment]
That might be what wolfgang42 was talking about in #8 

I guess it'll be fixed soon enough.

**Comment by chancezeus** [comment]
Ran into the same issue, going through the code I see that for each release it creates a manual rewrite (as mentioned in issue #8) which requires the nginx server to be reloaded.

I think it would be easier/better to do something like:
```
rewrite ^/pool/any/main/v/vagrant/vagrant_([^_]+)_i386.deb https://releases.hashicorp.com/vagrant/$1/vagrant_$1_i686.deb permanent;
rewrite ^/pool/any/main/v/vagrant/vagrant_([^_]+)_amd64.deb https://releases.hashicorp.com/vagrant/$1/vagrant_$1_x86_64.deb permanent;
```

In the main vhost config, that way (unless the release uri format changes), the server does not have to be reloaded and the download should work as soon as the repository info files are updated

**Comment by wolfgang42** [comment]
Thanks everyone for letting me know about this issue. @JanSchnacki is right, this is #8 again. I thought I fixed this but evidently not.

I've reloaded the server config, so this is working again, and I will close this in favor of #8.
