### ISSUE TITLE
vagrant 2.2.5

### ISSUE THREAD

**Issue by Mte90** [wolfgang42/vagrant-deb#17]
the latest release is of 19 june as say the changelog https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md
Instead the repo is updated for 2.2.4

**Comment by wolfgang42** [comment]
Thanks for noticing this! It looks like the cron job has stopped running,
but I'm not sure why. I'll investigate further this evening.

**Comment by Mte90** [comment]
Thank you for the repo :-D

**Comment by wolfgang42** [comment]
I accidentally deleted the line in the crontab while doing some other work on the server and didn't notice. I put it back and I think everything's good now. Thanks again for catching this, and I'm glad you find the repo helpful!
