### ISSUE TITLE
Wrong last version on page

### ISSUE THREAD

**Issue by Mte90** [wolfgang42/vagrant-deb#18]
On https://vagrant-deb.linestarve.com/ says that is 2.2.9 but instead is 2.2.14 the latest version.

**Comment by wolfgang42** [comment]
Oops, looks like I've been caught out by incorrect sorting. From the `releases.json`:

```json
  "2.2.0",
  "2.2.1",
  "2.2.10",
  "2.2.11",
  "2.2.12",
  "2.2.13",
  "2.2.14",
  "2.2.2",
  "2.2.3",
  "2.2.4",
  "2.2.5",
  "2.2.6",
  "2.2.7",
  "2.2.8",
  "2.2.9"
```

I'll try to fix this soon, but in the meantime rest assured that the actual version in the apt repo is up-to-date, this is just a display issue.

**Comment by Mte90** [comment]
Perfect!
