### ISSUE TITLE
InRelease file expired

### ISSUE THREAD

**Issue by Mte90** [wolfgang42/vagrant-deb#19]
I am getting this error in `apt update`, says that the file is expired since `20h 46min 27s`.

**Comment by logoff** [comment]
Long version of the error:

> E: Release file for https://vagrant-deb.linestarve.com/dists/any/InRelease is expired (invalid since 19h 36min 36s). Updates for this repository will not be applied.

Indeed, the InRelease file has expired:
```
curl -s https://vagrant-deb.linestarve.com/dists/any/InRelease | grep Valid-Until
Valid-Until: Thu, 14 Jan 2021 12:17:24 UTC
```

**Comment by wolfgang42** [comment]
Thanks for letting me know about this; should be fixed now. (The server had a problem and the updater stopped running.)

**Comment by codekandis** [comment]
It was working again today but currently ...

```
Err:10 https://vagrant-deb.linestarve.com any InRelease                                                                                                                                                                         
  503  Service Temporarily Unavailable [IP: 199.38.183.38 443]
```

**Comment by wolfgang42** [comment]
That 503 error is an attempt to notify people of the upcoming decommissioning of this repository, as [described on the repository homepage](https://vagrant-deb.linestarve.com/), so they can migrate to the new official repo from HashiCorp. It will go away tomorrow, but in the meantime you should probably follow the instructions to switch over to the new repo.

(This is related to the InRelease file expiring only in that fixing that prompted me to get around to writing up instructions on how to switch and come up with a definite timeline for shutting of this repo. I've just written up a separate issue, #22, for people who get this error and come to the issues list for info.)

**Comment by codekandis** [comment]
Aight ... so I will.

**Thank you very much for maintaining the repo over the years. I really much appreciate it.**

**Comment by Mte90** [comment]
Thanks I didn't know that now they have a debian repo too. I will update my machines.
