### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by ervoiox** [wolfgang42/vagrant-deb#4]
Hi @wolfgang42,

http://vagrant-deb.linestarve.com/ appears to be offline? Only temporarily I hope.

**Comment by wolfgang42** [comment]
Thanks for letting me know! It looks like [Apache crashed during an update](http://askubuntu.com/questions/777366/are-updates-to-libapache2-mod-php5-update-causing-apache-to-crash). I've restarted the server.
