### ISSUE TITLE
apt complains about weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by teohhanhui** [wolfgang42/vagrant-deb#5]
> W: http://vagrant-deb.linestarve.com/dists/any/InRelease: Signature by key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4 uses weak digest algorithm (SHA1)

Please upgrade aptly to 0.9.7

smira/aptly#366

**Comment by wolfgang42** [comment]
Thanks for letting me know!

The server had aptly 0.9.7, but since no Vagrant updates have come out recently the package lists hadn't been rebuilt. I've republished the repository using the newer version of aptly.
