### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by roelbindels** [wolfgang42/vagrant-deb#6]
Looks like the server is down.

**Comment by wolfgang42** [comment]
Indeed! The network interface is up, but no packets are getting through. I've opened a ticket with my hosting provider. SLA 0-2 hours, but they usually respond within 15 minutes even to low-priority questions.

**Comment by wolfgang42** [comment]
Their network lost the firewall rules for my server somehow. They've fixed the problem, so the repository is back up again, and are investigating the cause.
