### ISSUE TITLE
gpgkeys: key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4 can't be retrieved

### ISSUE THREAD

**Issue by vl-ivanov** [wolfgang42/vagrant-deb#9]
Hello!

I am trying to setup the repo on my Ubuntu 16.04 desktop, but I have troubles inserting the key.
Please refer to the command output for details:

> $ sudo apt-key adv --keyserver pgp.mit.edu --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
Executing: /tmp/tmp.BNY8FAnNRf/gpg.1.sh --keyserver
pgp.mit.edu
--recv-key
AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
gpg: requesting key 2099F7A4 from hkp server pgp.mit.edu
gpgkeys: key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm

**Comment by wolfgang42** [comment]
I have never encountered this error before, but from what I read it may indicate a temporary problem with the MIT keyserver. Can you try again and see if the problem persists? The other possibility apparently is that `apt-key` has problems with proxy servers, so if you're behind one you may need to look into alternative ways of getting the keys.

If this doesn't help then apparently the following command may provide more indications about what has gone wrong:

    gpg --keyserver keyserver.ubuntu.com --recv-keys AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4

**Comment by wolfgang42** [comment]
Closing as I haven't heard back for 1 month. Please reopen if you encounter this problem again.

**Comment by jangroth** [comment]
I experienced the same issue. Using a different keyserver solved the problem.

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4`

**Comment by wolfgang42** [comment]
I can confirm that I'm currently seeing the same problem. I think I'll change the command to use the ubuntu keyservers instead.
